client_id = "088383db419081f78771e3cdc36ce709"
name = "Bharat Loyalty Rewards"
application_url = "https://bharat-loyalty-rewards.onrender.com"
embedded = true

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/orders/create"
  topics = [ "orders/create" ]

[access_scopes]
scopes = "read_orders,write_discounts,write_metaobject_definitions,write_metaobjects,write_orders,write_products"

[auth]
redirect_urls = [ "https://bharat-loyalty-rewards.onrender.com/auth/callback" ]

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[app_proxy]
url = "https://bharat-loyalty-rewards.onrender.com"
subpath = "rewards"
prefix = "apps"
